server:
  port: 8999

spring:
  application:
    name: springcloud-demo
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

### apollo server的应用id
app:
  id: springcloud-demo

apollo:
  bootstrap:
    enabled: true
  #meta: http://apollo.muguangli.cn:8080
  meta: http://localhost:8080

env: DEV
